services:
  api1:
    build: .
    hostname: "api1"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"


