services:
  api1:
    build: "./app"
    hostname: "api1"
    expose:
      - "80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"


