services:
  api1:
    hostname: "api1"
    build: .
    expose: 
      - "80"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/apidb"
    depends_on:
      - db

  nginx:
    hostname: "nginx"
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:80"

  db:
    hostname: "db"
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"
    volumes:
      # - api-db:/var/lib/postgresql/data
      - ./db/seed.sql:/docker-entrypoint-initdb.d/init.sql


